export const EDIT = "EDIT";
export const SIGNUP = "SIGNUP";
export const LOGIN = "LOGIN";
export const SIGNUP_FORM = "SIGNUP_FORM";
export const LOGIN_FORM = "LOGIN_FORM";
export const HIDE_FORM = "HIDE_FORM";
export const DESCRIPTION = "DESCRIPTION";
export const CATEGORY = "SET_CATEGORY";
export const TOCART = "TO_CART";
export const TOLIST = "TO_LIST";
export const SEARCH = "SEARCH";
export const STORE_REGISTERED_USER_DATA ="STORE_REGISTERED_USER_DATA";
export const LOGGEDUSER = "LOGGEDUSER";
export const ERROR = "ERROR";
export const LOADER = 'LOADER'